name: Outputs Demo
on: push
jobs:
  build:
    outputs:
      version: ${{ steps.id-1-1-0.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: step-1-build
        id: id-1-1-0
        run: echo "version=1.0.0" >> $GITHUB_OUTPUT
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: step-2-DeployTheApp
        run: echo "We are deployin the app with version ${{ needs.build.outputs.version }}"
